// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PoolManager.IntegrationTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PoolManagerFeatureFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "PoolManagerFeature.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PoolManagerFeature", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "PoolManagerFeature")))
            {
                global::PoolManager.IntegrationTests.PoolManagerFeatureFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("pool start creates service instances with provided configuration")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PoolManagerFeature")]
        public virtual void PoolStartCreatesServiceInstancesWithProvidedConfiguration()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("pool start creates service instances with provided configuration", null, ((string[])(null)));
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
 testRunner.Given("the service fabric application name \"fabric:/PoolManager.Tests\" for type \"PoolMan" +
                    "ager.Tests\" exists with no services", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.And("the service fabric application type \"PoolManager.Tests\" has \"NoOp\" service type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
 testRunner.And("the service pool \"fabric:/PoolManager.Tests/NoOp\" does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "IsServiceStateful",
                        "true"});
            table1.AddRow(new string[] {
                        "HasPersistedState",
                        "true"});
            table1.AddRow(new string[] {
                        "MinReplicas",
                        "1"});
            table1.AddRow(new string[] {
                        "TargetReplicas",
                        "3"});
            table1.AddRow(new string[] {
                        "PartitionScheme",
                        "Singleton"});
            table1.AddRow(new string[] {
                        "MaxPoolSize",
                        "10"});
            table1.AddRow(new string[] {
                        "IdleServicesPoolSize",
                        "3"});
            table1.AddRow(new string[] {
                        "ServicesAllocationBlockSize",
                        "2"});
            table1.AddRow(new string[] {
                        "ExpirationQuanta",
                        "00:03:00"});
#line 7
 testRunner.When("the \"fabric:/PoolManager.Tests/NoOp\" pool is started with the following configura" +
                    "tion", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "ExpirationQuanta",
                        "00:03:00"});
            table2.AddRow(new string[] {
                        "HasPersistedState",
                        "true"});
            table2.AddRow(new string[] {
                        "IdleServicesPoolSize",
                        "3"});
            table2.AddRow(new string[] {
                        "IsServiceStateful",
                        "true"});
            table2.AddRow(new string[] {
                        "MaxPoolSize",
                        "10"});
            table2.AddRow(new string[] {
                        "MinReplicaSetSize",
                        "1"});
            table2.AddRow(new string[] {
                        "PartitionScheme",
                        "Singleton"});
            table2.AddRow(new string[] {
                        "ServicesAllocationBlockSize",
                        "2"});
            table2.AddRow(new string[] {
                        "ServiceTypeUri",
                        "fabric:/PoolManager.Tests/NoOp"});
            table2.AddRow(new string[] {
                        "TargetReplicasetSize",
                        "3"});
#line 18
 testRunner.Then("the \"fabric:/PoolManager.Tests/NoOp\" pool configuration should be", ((string)(null)), table2, "Then ");
#line 30
 testRunner.And("there should be \"3\" service instances for service fabric application \"fabric:/Poo" +
                    "lManager.Tests\" and service type \"NoOp\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.When("one of the \"fabric:/PoolManager.Tests/NoOp\" services moves", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "MinReplicaSize",
                        "1"});
            table3.AddRow(new string[] {
                        "TargetReplicaSize",
                        "3"});
            table3.AddRow(new string[] {
                        "PartitionScheme",
                        "Singleton"});
            table3.AddRow(new string[] {
                        "IsServiceStateful",
                        "true"});
            table3.AddRow(new string[] {
                        "HasPersistedState",
                        "true"});
#line 32
 testRunner.And("each service fabric application \"fabric:/PoolManager.Tests\" and service type \"NoO" +
                    "p\" instance should have the following configuration", ((string)(null)), table3, "And ");
#line 39
 testRunner.And("each service fabric application \"fabric:/PoolManager.Tests\" and service type \"NoO" +
                    "p\" instance partition should be healthy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
